apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: owdev-openwhisk
  name: owdev-action-proxy-pvc
  namespace: openwhisk
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: all-nfs
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: owdev-openwhisk
  name: owdev-copy-to-pvc
  namespace: openwhisk
spec:
  restartPolicy: Never
  containers:
  - image: alexmerenstein/f3-action-proxy:0.0.1
    command: ["cp", "/proxy", "/action-proxy/proxy"]
    name: test
    volumeMounts:
    - mountPath: /action-proxy
      name: pvc
  volumes:
  - name: pvc
    persistentVolumeClaim:
      claimName: owdev-action-proxy-pvc
